### ISSUE TITLE
twitter:description meta depends on post_excerpt

### ISSUE THREAD

**Issue by krisphelps** [postpromoterpro/post-promoter-pro#147]
Hey there,

I sent a support request using the form last night, but researched further when I got up this morning. Not sure if you'll consider this an issue or not. To generate the Twitter meta tags for card support, PPP relies on post_excertp in includes/twitter-functions.php on line 665.

Because many posts start with an image, WordPress doesn't return the image code in the excerpt (thankfully), but this truncates the description or even leaves the tag completely empty which breaks Twitter card functionality.

I use Yoast SEO to generate my excerpt, but it doesn't appear that Yoast SEO stores this on the post in the post_excerpt field.

Any ideas? One work around I found was to turn off Twitter Card functionality in PPP and let Yoast SEO inject the Twitter metas, but that might be confusing to less technical users.

**Comment by cklosowski** [comment]
Should be able to fix that. I'll work on something. Thanks for the report.

**Comment by krisphelps** [comment]
Awesome! You're doing a great job. PPP is a fantastic product.

**Comment by cklosowski** [comment]
@krisphelps Without an excerpt, PPP then goes to the content and pulls the first 200 characters of the post content, finds the last space, and then splits on that (so it doesn't end in the middle of a word).

Is there a place i can see the `description` not being generated?

**Comment by krisphelps** [comment]
How does it handle if the first 200 characters are all html? I believe that
is the situation I'm running into. I believe it counts the html still, but
then strips it. If that's the case it might be better to strip the html
first, then grab the 200 characters.

Alternatively, what about grabbing the meta description from the popular
plugins like Yoast SEO, and Genesis meta description? Just some ideas.

**Comment by cklosowski** [comment]
Yeah i'll look into supporting external functions if possible...let me get something written up here.

**Comment by cklosowski** [comment]
I think for now I'm going to strip the tags prior to truncating it. Seems that the Yoast data is inaccessible without them injecting the Twitter content.
