### ISSUE TITLE
Low quality images when tweeted

### ISSUE THREAD

**Issue by sumobi** [postpromoterpro/post-promoter-pro#169]
When an image is tweeted from PPP the quality is rather low. If you look closely at this screenshot you can see the pixellation around the text.

![screen shot 2016-05-28 at 6 15 56 pm](https://cloud.githubusercontent.com/assets/52581/15625583/64771c8c-2500-11e6-89b2-5f1cc49b7fe3.png)

**Comment by cklosowski** [comment]
@sumobi what are the original image dimensions when uploaded?

**Comment by sumobi** [comment]
@cklosowski usually very 1200x600 or 800x400. If I manually tweet with the exact same image used it comes out looking fine.

**Comment by sumobi** [comment]
Maybe it's just the size that needs to be bigger. Here's an example of a normal image, and one tweeted by PPP (first one). They actually both look to be pixelated, however PPP's image is smaller.

![screen shot 2016-06-04 at 11 27 21 am](https://cloud.githubusercontent.com/assets/52581/15795611/571eb08a-2a47-11e6-80b5-a8fb61662bf5.png)
___
Now look what happens in my Twitter feed if I click the PPP generated image to enlarge, it doesn't enlarge the image by very much, which is the sole purpose of clicking an image in the feed:

![screen shot 2016-06-04 at 11 30 34 am](https://cloud.githubusercontent.com/assets/52581/15795659/cb04ebae-2a47-11e6-8b7f-a6feb9c910cf.png)

___

And here's a normal image when clicked:

![screen shot 2016-06-04 at 11 30 54 am](https://cloud.githubusercontent.com/assets/52581/15795666/de85d7e2-2a47-11e6-8f32-5a727324840f.png)

**Comment by cklosowski** [comment]
I'm updating to be the 'requested sizes' from Twitter themselves...we'll see if that fixes it in #173
