### ISSUE TITLE
Invalid argument for foreach

### ISSUE THREAD

**Issue by cklosowski** [postpromoterpro/post-promoter-pro#170]
`[27-May-2016 16:12:36 UTC] PHP Warning:  Invalid argument supplied for foreach() in <...>/post-promoter-pro/includes/cron-functions.php on line 57`

**Comment by rumspeed** [comment]
If this helps, here are a few entries from the error log on one of our sites:
`[Tue Jun 07 08:16:23 2016] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: stderr: PHP Warning:  Invalid argument supplied for foreach() in /home/sitename/public_html/wp-content/plugins/post-promoter-pro/includes/cron-functions.php on line 57, referer: http://sitename.org/wp-admin/edit.php
[Tue Jun 07 08:16:55 2016] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: stderr: PHP Warning:  Invalid argument supplied for foreach() in /home/sitename/public_html/wp-content/plugins/post-promoter-pro/includes/cron-functions.php on line 57, referer: http://sitename.org/wp-admin/post.php?post=2847&action=edit
[Tue Jun 07 08:54:56 2016] [warn] [client xxx.xxx.xxx.xxx] mod_fcgid: stderr: PHP Warning:  Invalid argument supplied for foreach() in /home/sitename/public_html/wp-content/plugins/post-promoter-pro/includes/cron-functions.php on line 57, referer: http://sitename.org/wp-admin/post.php?post=3019&action=edit`

**Comment by cklosowski** [comment]
Ok, this should be resolved in 2.3 as the method of removing scheduled items has changed to support sharing to multiple networks. Closing out.
