### ISSUE TITLE
Google+ Integration

### ISSUE THREAD

**Issue by fxbenard** [postpromoterpro/post-promoter-pro#201]
Will be nice to have a way to push our content on Google+

**Comment by cklosowski** [comment]
@fxbenard Until they open up a public endpoint for publishing, this will remain on the backburner as not possible. The only way this happens is to be an approved partner for Google+ and so far there isn't an open policy on how to do this.

**Comment by fxbenard** [comment]
Thanks for the comment, I didn't know about that.

**Comment by cklosowski** [comment]
No problem! I'd love to support it and I keep an active eye on the APIs and
announcements around it, so if it comes up, I'll for sure look at
integrating. There are a few ways I 'could' do it currently but neither are
official and are a bit 'hacky', so I thought it best to avoid them, for now.

Chris Klosowski
cklosowski@gmail.com
@cklosowski

**Comment by cklosowski** [comment]
A little update. I've requested access to the Pages API. This won't allow posting to an individual's stream, but a page's stream. The catch is, all I can do is submit the request, if they deny me we hear nothing. They only respond if you are accepted. So far no response. Will keep this open to keep updates.

**Comment by krisphelps** [comment]
It's probably safe to close this one. https://techcrunch.com/2019/04/02/rip-google-see-you-on-friendfeed/

**Comment by cklosowski** [comment]
Yep, totally safe to close. I finally got the notice that my request for an app was declined :laughing: ...they must have had a queue of these sitting there.

**Comment by krisphelps** [comment]
> Yep, totally safe to close. I finally got the notice that my request for an app was declined 😆 ...they must have had a queue of these sitting there.

The irony of that is not lost on me.
