### ISSUE TITLE
Duplicate schedules

### ISSUE THREAD

**Issue by flowdee** [postpromoterpro/post-promoter-pro#204]
Would be very handy if I can duplicate single schedules on the post edit screen: After setting up the first post schedule clicking on a button which duplicates the schedule and I only have to update the date/time. Title + selected image should already be filled out.

**Comment by cklosowski** [comment]
This is a cool ideal. I'll milestone it and see what I can come up with.

**Comment by cklosowski** [comment]
![screen shot 2016-11-01 at 9 36 17 pm](https://cloud.githubusercontent.com/assets/1390124/19916846/41286c58-a07b-11e6-96a6-edc94138262a.png)

**Comment by cklosowski** [comment]
Found a small bug in where the duplicated share is actually put below the 'new row' that's created, just need to insert it before that new row.
