### ISSUE TITLE
Supported Post Types: Pages

### ISSUE THREAD

**Issue by flowdee** [postpromoterpro/post-promoter-pro#205]
Any special reasons why I shouldn't be able to share pages as well? I'm collecting many informations on pages I would like to share too.

**Comment by cklosowski** [comment]
There is a filter in place that would allow adding `pages` to the list of supported post types. I'll work on getting it into the next release. In the meantime you can use this little snippet:
```
function flowdee_add_pages( $post_types ) {
	$pages = new StdClass();
	$pages->labels = new StdClass();
	$pages->labels->name = 'Pages';
	$post_types['page'] = $pages;

	return $post_types;
}
add_filter( 'ppp_supported_post_types', 'flowdee_add_pages', 10, 1 );
```

The main reason for it missing, is that WordPress core doesn't return `page` in the list of items when you call `get_post_types()`. It's not something that I specifically chose to exclude, just an oversight in what was returned from that WP core function. Thanks for the heads up!

**Comment by flowdee** [comment]
Thanks! Looking forward to have it in the next release too :)
