### ISSUE TITLE
LinkedIn API update

### ISSUE THREAD

**Issue by ghost1227** [postpromoterpro/post-promoter-pro#209]
Since last year, the LinkedIn API no longer supports the `rw_nus` permission (though it's grandfathered for accounts which pre-date the change). Now, `w_share` is needed instead.

https://developer.linkedin.com/support/developer-program-transition

**Comment by cklosowski** [comment]
Thanks, I had updated this on the PPP Auth Proxy side, but missed the self hosted tokens one. Appreciate that.

**Comment by ghost1227** [comment]
Yep... I ran into that one...
