### ISSUE TITLE
Calculate Twitter character count on initial page load

### ISSUE THREAD

**Issue by nosegraze** [postpromoterpro/post-promoter-pro#227]
This isn't a huge deal, but I thought it a bit strange to see the count listed as 0. Obviously it's fixed when I type in there again, but it might make more sense to show the count on the initial page load too.

![ppp-arcs](https://cloud.githubusercontent.com/assets/6324272/20037213/5c0da8ee-a413-11e6-8518-ad79ea0e9975.png)

**Comment by cklosowski** [comment]
Well, this used to happen @nosegraze, I must have broken it somewhere along the line. I'll get that fixed up.
