### ISSUE TITLE
Make CSS selector more specific

### ISSUE THREAD

**Issue by sumobi** [postpromoterpro/post-promoter-pro#249]
PPP's `/post-promoter-pro/includes/scripts/css/admin-style.css` file is adding the following style:

```
.column-image img {
    width: 100%;
}
```

This is making all images in the image column 100% wide which is conflicting with AffiliateWP's image column: https://github.com/AffiliateWP/AffiliateWP/issues/2081

I propose changing the CSS selector so it's more specific to PPP. Prepending the selector with the table class seems like a good idea to me.

**Comment by cklosowski** [comment]
Sounds good. Will get a point release together.
-- 
Chris Klosowski
cklosowski@gmail.com
@cklosowski

**Comment by sumobi** [comment]
@cklosowski Found one other selector:

```
.socialmediaservices .icon.column-icon, .avatar.column-avatar, .name.column-name, .actions.column-actions, .extras.column-extras {
     vertical-align: middle;
}
```
The `.name.column-name` in the above rule will also need to be more specific since it's aligning a column in AffiliateWP.
