### ISSUE TITLE
Ability to 'Pin this tweet' option when sharing to Twitter

### ISSUE THREAD

**Issue by cklosowski** [postpromoterpro/post-promoter-pro#253]

**Comment by inetbiz** [comment]
Should also look into Tweet location

**Comment by cklosowski** [comment]
@inetbiz that's a good idea, I'll see if I can get that included in a separate enhancement.

**Comment by cklosowski** [comment]
Looks like the Twitter API isn't going to support pinning:
https://twittercommunity.com/t/pin-a-tweet-with-the-twitter-api/13048/7
