### ISSUE TITLE
PHP Error on User Profile Edit screen

### ISSUE THREAD

**Issue by d4mation** [postpromoterpro/post-promoter-pro#261]
The plugin has not been configured at all yet, so I'm not sure if connecting a Twitter account would prevent it. However, it probably shouldn't attempt to load if the data isn't present in that case.

The resulting PHP Error prevents some aspects of the User Profile Edit screen, such as the ability to change a password. The input does not show after clicking the "Generate Password" button.

Post Promoter Pro Version: `2.2.7`
WordPress Version: `4.8.1`
PHP Version: `7.0.22-0ubuntu0.16.04.1`

```
Notice: Constant PPP_LOCAL_TOKENS already defined in /nas/content/live/remote_site/wp-content/plugins/post-promoter-pro/includes/share-functions.php on line 154

Notice: Undefined property: PPP_Twitter_User::$twitter in /nas/content/live/remote_site/wp-content/plugins/post-promoter-pro/includes/libs/twitter-user.php on line 128

Fatal error: Uncaught Error: Call to a member function getRequestToken() on null in /nas/content/live/remote_site/wp-content/plugins/post-promoter-pro/includes/libs/twitter-user.php:128 Stack trace: #0 /nas/content/live/remote_site/wp-content/plugins/post-promoter-pro/includes/twitter-functions.php(721): PPP_Twitter_User->get_auth_url('http://goodshep...') #1 [internal function]: ppp_tw_profile_settings(Object(WP_User)) #2 /nas/content/live/remote_site/wp-includes/class-wp-hook.php(298): call_user_func_array('ppp_tw_profile_...', Array) #3 /nas/content/live/remote_site/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #4 /nas/content/live/remote_site/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /nas/content/live/remote_site/wp-admin/user-edit.php(647): do_action('edit_user_profi...', Object(WP_User)) #6 {main} thrown in /nas/content/live/remote_site/wp-content/plugins/post-promoter-pro/includes/libs/twitter-user.php on line 128
```

**Comment by d4mation** [comment]
Also, some similar notices appear on the Social Settings page. I am not declaring that Constant in my `wp-config.php` or anywhere else.

```
Notice: Constant PPP_LOCAL_TOKENS already defined in /nas/content/live/goodshepradio/wp-content/plugins/post-promoter-pro/includes/share-functions.php on line 154

Notice: Use of undefined constant PPP_FB_APP_ID - assumed 'PPP_FB_APP_ID' in /nas/content/live/goodshepradio/wp-content/plugins/post-promoter-pro/includes/libs/facebook.php on line 40

Notice: Use of undefined constant PPP_FB_APP_SECRET - assumed 'PPP_FB_APP_SECRET' in /nas/content/live/goodshepradio/wp-content/plugins/post-promoter-pro/includes/libs/facebook.php on line 41
```

**Comment by cklosowski** [comment]
Ill look into this.

If you are using this without a license key, you need to define the tokens
with the supplied smaller JSON file.  Have you done either of those?

**Comment by d4mation** [comment]
A license key has been entered, but I have not defined any tokens yet.

Should the JSON file still be used even if a license key is entered?

**Comment by cklosowski** [comment]
With a license it should call home for tokens. No JSON file necessary (it
was a way to easily allow collaboration).

Can you shoot me a support ticket with your license key so I can verify its
passing the proper checks?

If you don't enter a license you can manually define the keys with the JSON
file.


On Sep 14, 2017 7:56 AM, "Eric Defore" <notifications@github.com> wrote:

A license key has been entered, but I have not defined any tokens yet.

Should the JSON file still be used even if a license key is entered?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/postpromoterpro/post-promoter-pro/issues/261#issuecomment-329508551>,
or mute the thread

**Comment by d4mation** [comment]
A ticket should have been opened referencing this GitHub issue. I did not open it personally though, so the name will be different.

**Comment by cklosowski** [comment]
Thanks @d4mation I'll take a look into it tonight to see if I can replicate it and get a fix out.

**Comment by cklosowski** [comment]
@d4mation are you still seeing this? I've tried and tried to replicate but cannot. I'm wondering if a 'checkin' for the api keys failed at some point.

I've got some initial work to try and avoid the duplicate constant definitions and making sure that some of the APIs are setup correctly before it tries to use them, but curious if this self resolved due to timing and API keys finally getting populated.

**Comment by d4mation** [comment]
Looks like if I go to the Settings Page for Post Promoter Pro it shows an "Activate" button for the License, but clicking that seems to do nothing. I don't have it showing PHP Errors at the moment, but I figure it is tied into the above problems. As a result, seems that I can't quickly pull in a new version to test :/

Is there a separate "dist" version of this Plugin that gets hosted out there, or should I be able to just clone this Repo to the site to test the fix? I don't have all the logins to get everywhere personally, so if cloning this Repo 1:1 to the server is the same as downloading the ZIP normally that would be faster for me to test.

**Comment by cklosowski** [comment]
@d4mation Yep, cloning this repo is all that is needed. It doesn't use a build procedure. The only difference from downloading the .zip from the site and cloning is that you'll get the unit test framework dependencies.

**Comment by d4mation** [comment]
Gave the `issue/261` branch a shot on Staging and got the following:

```
Fatal error: Uncaught Error: Call to a member function getRequestToken() on null in /nas/content/staging/remote_site/wp-content/plugins/post-promoter-pro/includes/libs/twitter-user.php:132 Stack trace: #0 /nas/content/staging/remote_site/wp-content/plugins/post-promoter-pro/includes/twitter-functions.php(896): PPP_Twitter_User->get_auth_url('http://goodshep...') #1 [internal function]: ppp_tw_profile_settings(Object(WP_User)) #2 /nas/content/staging/remote_site/wp-includes/class-wp-hook.php(298): call_user_func_array('ppp_tw_profile_...', Array) #3 /nas/content/staging/remote_site/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters(NULL, Array) #4 /nas/content/staging/remote_site/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #5 /nas/content/staging/remote_site/wp-admin/user-edit.php(638): do_action('show_user_profi...', Object(WP_User)) #6 /nas/content/staging/remote_site/wp-admin/profile.php(18): require_once('/nas/content/st...') #7 {main} thrown in /nas/content/staging/remote_site/wp-content/plugins/post-promoter-pro/includes/libs/twitter-user.php on line 132
```

**Comment by cklosowski** [comment]
@d4mation I'm really confused as to how that's happening. Is the main Twitter account still disconnected?

**Comment by d4mation** [comment]
There are no connections currently. The plugin is simply active.

> The plugin has not been configured at all yet, so I'm not sure if connecting a Twitter account would prevent it. However, it probably shouldn't attempt to load if the data isn't present in that case.

**Comment by cklosowski** [comment]
@d4mation Ok, I was just making sure that hadn't changed.
