### ISSUE TITLE
public access to ppp-social-tokens.json on nginx

### ISSUE THREAD

**Issue by cfoellmann** [postpromoterpro/post-promoter-pro#268]
When you use the `ppp-social-tokens.json` file to set your applications nothing is preventing public access if .htaccess is not interpreted.
`http://site1.multisite-test.local/wp-content/uploads/sites/2/ppp/ppp-social-tokens.json` gives you the plain file.

At least a warning in the readme should be added.

**Comment by cklosowski** [comment]
Added in https://github.com/postpromoterpro/post-promoter-pro/commit/002bd567d37eb02d806d88fef2129bf103d3590d

**Comment by cklosowski** [comment]
@cfoellmann thanks for the report. As found working with EDD, there isn't a way to prevent this access via PHP, so i've added the rules that are needed to be placed on the nginx `server` configuration to stop access to the file.
