### ISSUE TITLE
Reference to 140 characters

### ISSUE THREAD

**Issue by ScottDeLuzio** [postpromoterpro/post-promoter-pro#271]
In the Post Promoter options page (Post Promoter > Post Promoter), if you click on the Default Text Tips link under the Default Share Text, it references Twitter's 140 character limit, which is now 280.

> The typical length of a link shortened on Twitter is 23 characters, so keep that in mind when writing your default text.	
Status updates over **_140 characters_** will fail to post.

I don't believe this is a functional issue (posts > 140 characters do post correctly), but could be confusing with the language inconsistency.

**Comment by cklosowski** [comment]
Good catch!
