### ISSUE TITLE
PPP Content Lost When Using Page Builder

### ISSUE THREAD

**Issue by ScottDeLuzio** [postpromoterpro/post-promoter-pro#274]
When using a page builder like Beaver Builder, PPP content does not save when the page is saved from the front end. More accurately, any existing PPP content is removed when a page is saved from the front end while data saved in other metaboxes (like Yoast) seems to be saved correctly. [Here is an example](http://somup.com/cbloDHVtvO).
In the Yoast example, I *believe* the data gets saved correctly because of how they save meta data on the `wp_insert_post` action (I could be wrong about that though). [Action](https://github.com/Yoast/wordpress-seo/blob/trunk/admin/metabox/class-metabox.php#L37) | [Function](https://github.com/Yoast/wordpress-seo/blob/trunk/admin/metabox/class-metabox.php#L795)

**Comment by cklosowski** [comment]
Going to have to dig deeper into this one. Changing the hook at which things are saved is a pretty big change. I think this might actually solve #231 as well, but so far I cannot get it to work correctly.

**Comment by cklosowski** [comment]
It doesn't look like this is causing any problems at this time. I'll include moving to `wp_insert_post` in the 2.4 for a beta release to make sure things are still working as expected.
