### ISSUE TITLE
Set `manage_options` as the default Capability for Admin Pages

### ISSUE THREAD

**Issue by d4mation** [postpromoterpro/post-promoter-pro#275]
Right now when adding Admin Pages, it checks for `administrator` which while effective in limiting it to Administrators, it makes granting access to other Roles without using the Filter less than desirable. `manage_options` seems to be a fairly standard check for Administrator Users, and if the Administrator Role were cloned to a separate Role with a few less permissions it would allow these menus to still show provided they have the `manage_options` Capability still.

I may be looking at it incorrectly, but it also seems that within many of these pages it checks whether the current user can `manage_options` anyhow, so restricting showing the Menu Items for that Capability may make sense as well.

https://github.com/postpromoterpro/post-promoter-pro/blob/9c9369ed511af1606ad17e8d4245c960724e7b3f/post-promoter-pro.php#L190

**Comment by cklosowski** [comment]
Thanks Eric, Will look into improving that.

Chris Klosowski
cklosowski@gmail.com
@cklosowski

**Comment by markjaquith** [comment]
Agree with @d4mation. Best practice here is `manage_options`. Some sites take away "Manage Options" from administrators but keep the plugin activation/deactivation capabilities, and then create a new role above Administrator that can change options. Or sometimes an account with the opposite (no plugin activation capabilities, but the ability to modify options... "Administrator Junior").

The good news is that changing this to `manage_options` shouldn't cause any issues, as for almost all sites, `administrator` will have `manage_options`.

**Comment by markjaquith** [comment]
(Sorry for the noise — I amended the commit a few times before making the pull request).
