### ISSUE TITLE
Missing closing tag in Pinterest metabox content causes wonky metabox display

### ISSUE THREAD

**Issue by nosegraze** [postpromoterpro/post-promoter-pro#294]
![rcp-metabox](https://user-images.githubusercontent.com/6324272/38814869-7b87435e-418a-11e8-8e0c-ed379a9f75e1.png)

All metaboxes under PPP kind of get merged into the PPP one and you can't expand any of them unless you expand PPP.

The issue is a missing `</div>` tag in the Pinterest metabox code. This tag never gets closed: https://github.com/postpromoterpro/post-promoter-pro/blob/master/includes/pinterest-functions.php#L47

Similarly, there's a missing `</p>` tag right above: https://github.com/postpromoterpro/post-promoter-pro/blob/master/includes/pinterest-functions.php#L46

**Comment by cklosowski** [comment]
:+1: Thanks @nosegraze will get that addressed here shortly.
