### ISSUE TITLE
PHP 7.2 warning: count(): Parameter must be an array or an object that implements Countable 

### ISSUE THREAD

**Issue by nosegraze** [postpromoterpro/post-promoter-pro#296]
https://github.com/postpromoterpro/post-promoter-pro/blob/master/includes/admin/welcome.php#L245

This:

```php
if ( count( $version_level > 2 ) ) {
```

Should be this:

```php
if ( count( $version_level ) > 2 ) {
```

**Comment by cklosowski** [comment]
Yeah I'm just going to kill the welcome page all together I think :) We've been moving away from them in EDD as well and I think it's just a far less 'jarring' experience for users.

**Comment by luke-au** [comment]
FYI: I am finding as this code currently stands it causes UI issues when uploading files in Media Library. 
The uploaded file is successfully added to the Media Library however In the "Crunching" phase the UI status stops updating and the error message is displayed:
> Warning: count(): Parameter must be an array or an object that implements Countable in /wp-content/plugins/post-promoter-pro/includes/admin/welcome.php on line 245
6531
