### ISSUE TITLE
No version bump added for Version 2.3.18, June 19, 2017

### ISSUE THREAD

**Issue by luke-au** [postpromoterpro/post-promoter-pro#303]
FYI No version bump added for Version 2.3.18, June 19, 2017.
WordPress keeps looking for the update as the code still says 2.3.17 and the server says 2.3.18 exists.

**Comment by cklosowski** [comment]
@luke-au, Looking into this now. Just seems like something got missed in the tag. I'll push up a new version now that should solve the problem. Thanks for the heads up.

**Comment by cklosowski** [comment]
@luke-au should be all set. Sorry about that. Looks like the tag GitHub release didn't work correctly. I started using those recently, to give more visibility than just Git tags, still getting used to that process. thanks for the heads up.
