### ISSUE TITLE
ppp_schedule_share() fails to schedule valid shares

### ISSUE THREAD

**Issue by ScottDeLuzio** [postpromoterpro/post-promoter-pro#304]
The ppp_schedule_share() function fails to add scheduled shares.
In troubleshooting, I added Tweets to a 'post' post type, which were saved in the metabox in the post edit page, but not to the PPP>Schedule page.

Also when troubleshooting, I saved a few variables to see what the function was evaluating.
`$allowed_post_types = array(1) { [0]=> string(4) "post" }` 
`$post->post_type = post`

In the function there is a check for array_key_exists:
```
if ( ! isset( $_POST['post_status'] ) || ! array_key_exists( $post->post_type, $allowed_post_types ) ) {
    return;
}
```
Except 'post' (from `$post->post_type`) is not an array key of `$allowed_post_types`. Changing `array_key_exists` to `in_array` allows the check to pass and schedule shares as expected.

**Comment by cklosowski** [comment]
For a note I haven't been able to replicate this yet. Going to milestone it for a minor point release, and investigate.
