### ISSUE TITLE
New connections not able to connect in some cases.

### ISSUE THREAD

**Issue by cklosowski** [postpromoterpro/post-promoter-pro#306]
@ScottDeLuzio had an issue connecting a new site, and got this:
`array(1) { [" string(189) ""1.0" encoding="UTF-8"?>Callback URL not approved for this client application. Approved callback URLs can be adjusted in your application settings" }`

Will have to see if Twitter changed something in their oAuth protocol.

**Comment by cklosowski** [comment]
So I'm digging into this and it's due to a recent change in the Twitter API. I have a fix that I'm working on but running into a few roadblocks. I'm about 80% done with it, just need to get one small thing working with the initial request token.

Right now there are a few workarounds, but they are painful, and I can supply them to users as they need. @ScottDeLuzio You uncovered a can of worms here ;). Going to have to do some magic to work through this as Twitter doesn't easily support an oAuth proxy like FaceBook and LinkedIn do. So I'm having to do a little bit of handy work for the process.

**Comment by cklosowski** [comment]
@ScottDeLuzio Do you mind giving this branch `issue/306` a shot? I think it should fix things for the Twitter authentication.

Just test the main settings. If this works fine I'll adopt it for the User Profile area as well.

**Comment by ScottDeLuzio** [comment]
When authorizing Twitter, I'm confused about where to enter the code I'm given. [The only links on the page after authorizing are to Twitter or to the PPP website](https://prnt.sc/k4xa9q). When I return back to the PPP settings page on my site there isn't any place to enter the code. Refreshing the settings doesn't give an input either.

**Comment by ScottDeLuzio** [comment]
Tried it again, and got the "enter your PIN" box to show up on my site. Might have been a JS error or something earlier on the site I was using it on, or a browser extension.
Except this time it won't let me submit the pin. Click the button and it doesn't seem like anything is happening.

**Comment by ScottDeLuzio** [comment]
In [ppp_custom.js](https://github.com/postpromoterpro/post-promoter-pro/blob/95f98d4ce6e0caffbea33f22f2c9b967411a09e5/includes/scripts/js/ppp_custom.js#L92) the response is 0 when the submit PIN button is clicked. The check is `if( response === '1' )` though, so it isn't reloading as expected.

**Comment by cklosowski** [comment]
@ScottDeLuzio That means that it didn't properly validate the PIN. That's the error handling I was talking about.

What browser extensions do you have going? I've found that a few chrome extensions make multiple header calls on the page, which modifies the Request Token.

Could you try in an incognito window that doesn't have the extensions active?

**Comment by ScottDeLuzio** [comment]
I got the same result using incognito w/ no extensions.

**Comment by cklosowski** [comment]
Ok, I'll dig more into it tonight, see what I can figure out @ScottDeLuzio.

**Comment by cklosowski** [comment]
@ScottDeLuzio Ok can you pull down `issue/306` and give this another shot? I think I've got it figured out.

**Comment by cklosowski** [comment]
Sweet thanks @ScottDeLuzio I'll get that move over to the user profile pages too and we should be good.

**Comment by cklosowski** [comment]
@ScottDeLuzio If you have a few, will you test out the profile connection as well?

I think I got it working on the `issue/306` branch.

**Comment by ScottDeLuzio** [comment]
PIN worked as expected on the profile connection as well. Looks good!
