### ISSUE TITLE
PHP error due to undefined Facebook constants

### ISSUE THREAD

**Issue by davisshaver** [postpromoterpro/post-promoter-pro#312]
Licensed customer but using the Github repo via composer for my builds.

I see an error from these two lines due to the constants being undefined: https://github.com/postpromoterpro/post-promoter-pro/blob/master/includes/libs/facebook.php#L40-L41

If I am using the license, do I need to still set `PPP_FB_APP_SECRET` and `PPP_FB_APP_ID`?

Example error:
```
Warning: Use of undefined constant PPP_FB_APP_ID - assumed 'PPP_FB_APP_ID' (this will throw an Error in a future version of PHP) in /Users/davisshaver/ppc-oo/public/site/wp-content/plugins/post-promoter-pro/includes/libs/facebook.php on line 40
```

**Comment by davisshaver** [comment]
I am going to file this as a support request.

**Comment by cklosowski** [comment]
@davisshaver Yep those should get pulled in weekly from the store using your license key, this is so it can publish to Facebook correctly.

**Comment by davisshaver** [comment]
@cklosowski For some reason they aren't defined for me. This diff fixes the undefined call but I haven't tested it much more than that yet. https://github.com/davisshaver/post-promoter-pro/commit/139409f98fcd9ce607a1255c34230cb018db0203.diff

**Comment by davisshaver** [comment]
@cklosowski Are you still maintaining this plugin? I've emailed you several times to no response. If you don't intend to support the plugin it seems slightly unethical to sell lifetime licenses. I would like a partial refund.

**Comment by cklosowski** [comment]
@davisshaver

I am and have recently released an update to fix some Facebook API issues.

I'm sorry I haven't seen your support issues hit my inbox, I was having issues with them getting makes as Spam in Gmail so let me take a look though them.

I'll take another look at this over the weekend.

**Comment by cklosowski** [comment]
@davisshaver I did however receive your most recent ticket BTW.

**Comment by davisshaver** [comment]
Thank you @cklosowski... if you are still supporting it that’s fine, I appreciate you explaining the delay. I will test the update this weekend.

**Comment by davisshaver** [comment]
@cklosowski I am having similar issues with Facebook API and pages not appearing in the dropdown. I notice that the site is down. Can you please reach out to me?

**Comment by cklosowski** [comment]
@davisshaver Emailed you back, sorry about the site having issues, I deployed a theme update and was apparently being served the cached version so it all looked fine, when it really wasn't.

Also sorry for the delay, you caught me on the first day of paternity leave, so I wasn't near a computer for most of it.

**Comment by davisshaver** [comment]
Congrats @cklosowski!!! Thank you for getting back to me. Will followup on email and we can close this one I think.
