### ISSUE TITLE
Warning: session_start(): Cannot send session cookie - headers already sent

### ISSUE THREAD

**Issue by pippinsplugins** [postpromoterpro/post-promoter-pro#319]
I've been seeing this notice repeatedly on sugarcalendar.com:

Warning: session_start(): Cannot send session cookie - headers already sent in /dom22245/wp-content/plugins/post-promoter-pro/includes/general-functions.php on line 19

**Comment by pippinsplugins** [comment]
There's a second, similar notice:

Warning: session_start(): Cannot send session cache limiter - headers already sent in /dom22245/wp-content/plugins/post-promoter-pro/includes/general-functions.php on line 19

**Comment by pippinsplugins** [comment]
I'm pretty baffled on this one. There's a `! headers_sent()` check but it seems to be failing but I can't see why.

**Comment by cklosowski** [comment]
Yep fixed this in master already. Saw it on AffWP and RCP. I'll get it
released soon.

**Comment by pippinsplugins** [comment]
:+1:
